"""Protocol and product constants for Snowlink MVP."""

from __future__ import annotations

PROTOCOL_VERSION = 1
DEFAULT_SIGNALING_PORT = 3847
MAX_SIGNALING_MESSAGE_BYTES = 256 * 1024

PAIRING_CODE_DIGITS = 6
PAIRING_TTL_S = 180.0
PAIRING_RATE_LIMIT_FAILURES = 5
PAIRING_RATE_LIMIT_WINDOW_S = 60.0
PAIRING_APPROVAL_TIMEOUT_S = 120.0

APP_NAME = "Snowlink"
